version: '3.1'
services:
  postgres:
    image: postgres:15-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: Postgres23456
      POSTGRES_DB: test
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Root23456
      - MYSQL_DATABASE=test
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=Admin23456
    volumes:
      - ./volumes/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rag
    restart: always
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=Admin#1234
      - TZ=Asia/Shanghai
    volumes:
      - ./volumes/minio/data:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - rag
    restart: always
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/data
      - /etc/localtime:/etc/localtime:ro
    command: redis-server --requirepass Redis23456
    networks:
      - rag
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Adjust the heap size if necessary
    volumes:
      - ./volumes/es/data:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - rag
    restart: always
  milvus:
    image: milvusdb/milvus:v2.4.1
    container_name: milvus
    command: milvus run standalone  1> /dev/null
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_USE_EMBED=true
      - ETCD_DATA_DIR=/var/lib/milvus/etcd 
      - ETCD_CONFIG_PATH=/milvus/configs/embedEtcd.yaml
      - COMMON_STORAGETYPE=local 
    volumes:
      - ./milvus/embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./volumes/milvus:/var/lib/milvus
      - /etc/localtime:/etc/localtime:ro 
    ports:
      - 19530:19530 
      - 9091:9091 
      - 2379:2379 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
    networks:
      - rag
    restart: always

networks:
  rag:
    driver: bridge
